### ISSUE TITLE
How to process the queue?

### ISSUE THREAD

**Issue by curana** [threez/file-queue#3]
Hi,

I implemented a simple example using the file-queue. I don't understand how I should process the queue. When I run "pop" it will just take one message from the queue and processes it.

So I understand that I need to take care of the queue itself, meaning that I need to check the length constantly and run pop by my own logic. It's not like pop is called whenever there is a new file in the queue, right?

Thanks for clarifying.

**Comment by threez** [comment]
*pop* acts like a *.once("itemInQueue")* event. You have to *pop* in a **loop**. If nothing is in the queue, the callback is deferred until something was put into the queue (it is listening on file system events here, using the maildir pattern). The system is allows concurrency with multiple producers and consumers in the same directory. Checking the length is not required.

If you want to decide yourself, if processing of an item was successful or not, use the *tpop* function.
In this example you can see a simple consumer loop implemented by recursion in the *QueueWorker* function:

```js
'use strict';

var Queue = require('../queue').Queue,
    queue;

function QueueWorker(queue) {
  queue.pop(function(err, message) {
    if (err) { throw err; }
    console.log(message);
    QueueWorker(queue); // loop using recusion
  });
}

queue = new Queue('.', function(err) {
  QueueWorker(queue); // start worker after queue is ready
});
```
